# - OhMyZsh -

export ZSH=~/.oh-my-zsh

HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="true"

ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

ZSH_THEME_AWS_PREFIX="["
ZSH_THEME_AWS_SUFFIX="]"

plugins=(
    asdf
    dotenv
    git
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# Prompt

setopt PROMPT_SUBST

parse_git_branch() {
    branch=$(git_current_branch)
    if [ ! -z $branch ];then
        echo '@'$branch
    fi
}

PROMPT=$'%{${fg[cyan]}%}%~%{${fg[magenta]}%}$(parse_git_branch)%{${fg[default]}%} '

# - Aliases -

alias ll='ls -l'
alias la='ls -a'
alias magick='nocorrect magick'
alias code='nocorrect code'

# iOS

alias recordSimulator='xcrun simctl io booted recordVideo ~/Desktop/video.mov'
alias rmDerivedData='rm -rf ~/Library/Developer/Xcode/DerivedData/'
alias sysDiagnoseSimulator='xcrun simctl diagnose'
alias videoToGif='ffmpeg -i ~/Desktop/video.mov ~/Desktop/video.gif && rm ~/Desktop/video.mov'

# Postgres
alias psqlStart='pg_ctl -D /usr/local/var/postgres start'
alias psqlStop='pg_ctl -D /usr/local/var/postgres stop'



